### ISSUE TITLE
Can't build in python 2.7

### ISSUE THREAD

**Issue by louischaman** [AndrewWalker/pydubins#4]
There seems to be an issue with the settings for the C-compiler. Not sure how to get it to compile.

C:\Python27_v2\Scripts>pip install dubins
Collecting dubins
  Using cached dubins-0.9.2.tar.gz
Installing collected packages: dubins
  Running setup.py install for dubins
    Complete output from command c:\python27_v2\python.exe -c "import setuptools
, tokenize;__file__='c:\\users\\louis~1.sch\\appdata\\local\\temp\\pip-build-x1d
jpg\\dubins\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).re
ad().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\louis~
1.sch\appdata\local\temp\pip-ffs7ho-record\install-record.txt --single-version-e
xternally-managed --compile:
    running install
    running build
    running build_ext
    skipping 'dubins\dubins.c' Cython extension (up-to-date)
    building 'dubins' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\dubins
    creating build\temp.win32-2.7\Release\dubins\src
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo
/Ox /MD /W3 /GS- /DNDEBUG -Idubins/include -Ic:\python27_v2\include -Ic:\python2
7_v2\PC /Tcdubins/src/dubins.c /Fobuild\temp.win32-2.7\Release\dubins/src/dubins
.obj
    dubins.c
    dubins/src/dubins.c(82) : error C2065: 'M_PI' : undeclared identifier
    dubins/src/dubins.c(87) : error C2065: 'INFINITY' : undeclared identifier
    dubins/src/dubins.c(125) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(126) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(127) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(133) : error C2065: 'alpha' : undeclared identifier
    dubins/src/dubins.c(133) : error C2065: 'beta' : undeclared identifier
    dubins/src/dubins.c(139) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(140) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(141) : error C2065: 'p_squared' : undeclared identifier
    dubins/src/dubins.c(144) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(145) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(146) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(147) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(148) : error C2065: 't' : undeclared identifier
    dubins/src/dubins.c(148) : error C2065: 'p' : undeclared identifier
    dubins/src/dubins.c(148) : error C2065: 'q' : undeclared identifier
    dubins/src/dubins.c(155) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(156) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(157) : error C2065: 'p_squared' : undeclared identifier
    dubins/src/dubins.c(160) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(161) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(162) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(163) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(164) : error C2065: 't' : undeclared identifier
    dubins/src/dubins.c(164) : error C2065: 'p' : undeclared identifier
    dubins/src/dubins.c(164) : error C2065: 'q' : undeclared identifier
    dubins/src/dubins.c(171) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(172) : error C2065: 'p_squared' : undeclared identifier
    dubins/src/dubins.c(175) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(176) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(177) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(178) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(179) : error C2065: 't' : undeclared identifier
    dubins/src/dubins.c(179) : error C2065: 'p' : undeclared identifier
    dubins/src/dubins.c(179) : error C2065: 'q' : undeclared identifier
    dubins/src/dubins.c(186) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(187) : error C2065: 'p_squared' : undeclared identifier
    dubins/src/dubins.c(190) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(191) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(192) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(193) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(194) : error C2065: 't' : undeclared identifier
    dubins/src/dubins.c(194) : error C2065: 'p' : undeclared identifier
    dubins/src/dubins.c(194) : error C2065: 'q' : undeclared identifier
    dubins/src/dubins.c(201) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(202) : error C2065: 'tmp_rlr' : undeclared identifier
    dubins/src/dubins.c(205) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(206) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(207) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(208) : error C2065: 't' : undeclared identifier
    dubins/src/dubins.c(208) : error C2065: 'p' : undeclared identifier
    dubins/src/dubins.c(208) : error C2065: 'q' : undeclared identifier
    dubins/src/dubins.c(215) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(216) : error C2065: 'tmp_lrl' : undeclared identifier
    dubins/src/dubins.c(219) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(220) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(221) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(222) : error C2065: 't' : undeclared identifier
    dubins/src/dubins.c(222) : error C2065: 'p' : undeclared identifier
    dubins/src/dubins.c(222) : error C2065: 'q' : undeclared identifier
    dubins/src/dubins.c(269) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(282) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(285) : error C2143: syntax error : missing ';' before 'c
onst'
    dubins/src/dubins.c(286) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(287) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(288) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(289) : error C2143: syntax error : missing ';' before 't
ype'
    dubins/src/dubins.c(290) : error C2065: 'p1' : undeclared identifier
    dubins/src/dubins.c(290) : error C2065: 'qi' : undeclared identifier
    dubins/src/dubins.c(290) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(290) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 2
    dubins/src/dubins.c(290) : error C2065: 'q1' : undeclared identifier
    dubins/src/dubins.c(290) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(290) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 3
    dubins/src/dubins.c(290) : error C2065: 'types' : undeclared identifier
    dubins/src/dubins.c(290) : error C2109: subscript requires array or pointer
type
    dubins/src/dubins.c(290) : error C2198: 'dubins_segment' : too few arguments
 for call
    dubins/src/dubins.c(291) : error C2065: 'p2' : undeclared identifier
    dubins/src/dubins.c(291) : error C2065: 'q1' : undeclared identifier
    dubins/src/dubins.c(291) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(291) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 2
    dubins/src/dubins.c(291) : error C2065: 'q2' : undeclared identifier
    dubins/src/dubins.c(291) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(291) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 3
    dubins/src/dubins.c(291) : error C2065: 'types' : undeclared identifier
    dubins/src/dubins.c(291) : error C2109: subscript requires array or pointer
type
    dubins/src/dubins.c(291) : error C2198: 'dubins_segment' : too few arguments
 for call
    dubins/src/dubins.c(292) : error C2065: 'tprime' : undeclared identifier
    dubins/src/dubins.c(292) : error C2065: 'p1' : undeclared identifier
    dubins/src/dubins.c(293) : error C2065: 'tprime' : undeclared identifier
    dubins/src/dubins.c(293) : error C2065: 'qi' : undeclared identifier
    dubins/src/dubins.c(293) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(293) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 2
    dubins/src/dubins.c(293) : error C2065: 'types' : undeclared identifier
    dubins/src/dubins.c(293) : error C2109: subscript requires array or pointer
type
    dubins/src/dubins.c(293) : error C2198: 'dubins_segment' : too few arguments
 for call
    dubins/src/dubins.c(295) : error C2065: 'tprime' : undeclared identifier
    dubins/src/dubins.c(295) : error C2065: 'p1' : undeclared identifier
    dubins/src/dubins.c(295) : error C2065: 'p2' : undeclared identifier
    dubins/src/dubins.c(296) : error C2065: 'tprime' : undeclared identifier
    dubins/src/dubins.c(296) : error C2065: 'p1' : undeclared identifier
    dubins/src/dubins.c(296) : error C2065: 'q1' : undeclared identifier
    dubins/src/dubins.c(296) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(296) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 2
    dubins/src/dubins.c(296) : error C2065: 'types' : undeclared identifier
    dubins/src/dubins.c(296) : error C2109: subscript requires array or pointer
type
    dubins/src/dubins.c(296) : error C2198: 'dubins_segment' : too few arguments
 for call
    dubins/src/dubins.c(299) : error C2065: 'tprime' : undeclared identifier
    dubins/src/dubins.c(299) : error C2065: 'p1' : undeclared identifier
    dubins/src/dubins.c(299) : error C2065: 'p2' : undeclared identifier
    dubins/src/dubins.c(299) : error C2065: 'q2' : undeclared identifier
    dubins/src/dubins.c(299) : warning C4047: 'function' : 'double *' differs in
 levels of indirection from 'int'
    dubins/src/dubins.c(299) : warning C4024: 'dubins_segment' : different types
 for formal and actual parameter 2
    dubins/src/dubins.c(299) : error C2065: 'types' : undeclared identifier
    dubins/src/dubins.c(299) : fatal error C1003: error count exceeds 100; stopp
ing compilation
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BI
N\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27_v2\python.exe -c "import setuptools, tokenize;__file__='c:\
\users\\louis~1.sch\\appdata\\local\\temp\\pip-build-x1djpg\\dubins\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record c:\users\louis~1.sch\appdata\local\temp
\pip-ffs7ho-record\install-record.txt --single-version-externally-managed --comp
ile" failed with error code 1 in c:\users\louis~1.sch\appdata\local\temp\pip-bui
ld-x1djpg\dubins
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**Comment by AndrewWalker** [comment]
Caused by the differences in the preprocessor definitions (and version of the c- standard) implemented by MSVC 9.
